# Generated by Django 5.0.4 on 2024-06-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0002_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
